services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $userRepository: '@swp.repository.user'
#            $userManager: 'SWP\Bundle\UserBundle\Model\UserManager'

#    SWP\Bundle\UserBundle\Controller\UserController:
#        tags: ['controller.service_arguments']
#
    SWP\Bundle\UserBundle\Controller\RegistrationController:
        tags: ['controller.service_arguments']

    SWP\Bundle\UserBundle\Controller\ProfileController:
        tags: ['controller.service_arguments']
