swp_user:
    resource: "@SWPUserBundle/Controller"
    type:     annotation

swp_user_registration_check_email:
    path: /register/check-email
    defaults: { _controller: SWP\Bundle\UserBundle\Controller\RegistrationController::checkEmailAction }

swp_user_registration_confirm:
    path: /register/confirm/{token}
    defaults: { _controller: SWP\Bundle\UserBundle\Controller\RegistrationController::confirmAction }

swp_user_registration_confirmed:
    path: /register/confirmed
    defaults: { _controller: SWP\Bundle\UserBundle\Controller\RegistrationController::confirmedAction }

swp_user_security_login:
    path: /register/confirmed
    defaults: { _controller: SWP\Bundle\UserBundle\Controller\RegistrationController::confirmedAction }

swp_user_registration_register:
    path: /
    defaults: { _controller: SWP\Bundle\UserBundle\Controller\RegistrationController::registerAction }
