services:
    swp_user.form.registration_type:
        class: SWP\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - "%swp.model.user.class%"
        tags:
            - { name: form.type }

    fos_user.user_manager:
        class: SWP\Bundle\UserBundle\Model\UserManager