parameters:
    swp_user.registration.confirmation.template : "@@SWPUser/Registration/email.txt.twig"
    swp_user.registration.confirmation.from_email : 'test.html.twig'
    swp_user.resetting.email.template :  "@@SWPUser/Resetting/email.txt.twig"
    swp_user.resetting.email.from_email : "contact@publisher.test:Publisher"
    swp_user.firewall_name: 'main'
#    swp_user.resetting.email.from_email:
#    spw_user.registration.from_email.resetting: "contact@publisher.test:Publisher"
#    spw_user.registration.from_email.confirmation: "contact@publisher.test:Publisher"
#    registration_from_email.confirmation: "contact@publisher.test:Publisher"
#    from_email:
#        address: '%env(FROM_EMAIL)%'
#        sender_name: Publisher
#    registration:
#        confirmation:
#            enabled: true


services:
    _defaults:
        autowire: true
        autoconfigure: true

    swp_user.form.registration_type:
        class: SWP\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - '%swp.model.user.class%'
        tags:
            - { name: form.type }

    SWP\Bundle\UserBundle\Model\UserManagerInterface: '@SWP\Bundle\UserBundle\Doctrine\UserManager'
    SWP\Bundle\UserBundle\Util\CanonicalizerInterface: '@SWP\Bundle\UserBundle\Util\Canonicalizer'

    SWP\Bundle\UserBundle\Util\Canonicalizer: ~
    SWP\Bundle\UserBundle\Doctrine\UserManager: '@swp_user.user_manager'

    swp_user.user_manager:
        class: 'SWP\Bundle\UserBundle\Doctrine\UserManager'
        public: true
        arguments:
            - '@SWP\Bundle\UserBundle\Util\PasswordUpdater'
            - '@SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater'
            - '@swp.object_manager.user'
            - '%swp.model.user.class%'


    SWP\Bundle\UserBundle\Util\PasswordUpdater:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface'

    SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater:
        arguments:
            - '@SWP\Bundle\UserBundle\Util\CanonicalizerInterface'
            - '@SWP\Bundle\UserBundle\Util\CanonicalizerInterface'

    SWP\Bundle\UserBundle\Doctrine\UserListener:
        arguments:
            - '@SWP\Bundle\UserBundle\Util\PasswordUpdater'
            - '@SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    SWP\Bundle\UserBundle\Util\UserManipulator: ~

    SWP\Bundle\UserBundle\EventListener\EmailConfirmationListener:
        arguments: ~
        tags:
            - { name: kernel.event_subscriber }

    SWP\Bundle\UserBundle\Mailer\Mailer:
        arguments:
                $tenantContext: '@swp_multi_tenancy.tenant_context'
                $mailer: '@swiftmailer.mailer.default'
                $parameters: { confirmation.template: 'test.html.twig',
                               resetting.template: 'test.html.twig',
                               from_email: { confirmation': 'test.html.twig', resetting: 'test.html.twig' }}


    SWP\Bundle\UserBundle\Mailer\MailerInterface: '@SWP\Bundle\UserBundle\Mailer\Mailer'

    swp_user.util.token_generator.default:
        class: SWP\Bundle\UserBundle\Util\TokenGenerator

    SWP\Bundle\UserBundle\Util\TokenGeneratorInterface: '@swp_user.util.token_generator.default'

    SWP\Bundle\UserBundle\Security\LoginManager: ~
    SWP\Bundle\UserBundle\Security\LoginManagerInterface: '@SWP\Bundle\UserBundle\Security\LoginManager'

    SWP\Bundle\UserBundle\EventListener\AuthenticationListener:
        arguments:
            $firewallName: '%swp_user.firewall_name%'
        tags:
            - { name: kernel.event_subscriber }
