parameters:
    swp_user.firewall_name: 'main'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    swp_user.form.registration_type:
        class: SWP\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - '%swp.model.user.class%'
        tags:
            - { name: form.type }

    SWP\Bundle\UserBundle\Model\UserManagerInterface: '@SWP\Bundle\UserBundle\Doctrine\UserManager'
    SWP\Bundle\UserBundle\Util\CanonicalizerInterface: '@SWP\Bundle\UserBundle\Util\Canonicalizer'

    SWP\Bundle\UserBundle\Util\Canonicalizer: ~
    SWP\Bundle\UserBundle\Doctrine\UserManager: '@swp_user.user_manager'

    swp_user.user_manager:
        class: 'SWP\Bundle\UserBundle\Doctrine\UserManager'
        public: true`
        arguments:
            - '@SWP\Bundle\UserBundle\Util\PasswordUpdater'
            - '@SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater'
            - '@swp.object_manager.user'
            - '%swp.model.user.class%'


    SWP\Bundle\UserBundle\Util\PasswordUpdater:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface'

    SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater:
        arguments:
            - '@SWP\Bundle\UserBundle\Util\CanonicalizerInterface'
            - '@SWP\Bundle\UserBundle\Util\CanonicalizerInterface'

    SWP\Bundle\UserBundle\Doctrine\UserListener:
        arguments:
            - '@SWP\Bundle\UserBundle\Util\PasswordUpdater'
            - '@SWP\Bundle\UserBundle\Util\CanonicalFieldsUpdater'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    SWP\Bundle\UserBundle\Util\UserManipulator: ~

    SWP\Bundle\UserBundle\EventListener\EmailConfirmationListener:
        arguments: ~
        tags:
            - { name: kernel.event_subscriber }

    SWP\Bundle\UserBundle\Mailer\MailerInterface: '@swp_user.mailer.default'

    swp_user.util.token_generator.default:
        class: SWP\Bundle\UserBundle\Util\TokenGenerator

    SWP\Bundle\UserBundle\Util\TokenGeneratorInterface: '@swp_user.util.token_generator.default'

    SWP\Bundle\UserBundle\Security\LoginManager: ~
    SWP\Bundle\UserBundle\Security\LoginManagerInterface: '@SWP\Bundle\UserBundle\Security\LoginManager'

    SWP\Bundle\UserBundle\EventListener\AuthenticationListener:
        arguments:
            $firewallName: '%swp_user.firewall_name%'
        tags:
            - { name: kernel.event_subscriber }
