SWP\Bundle\UserBundle\Model\User:
    type:  mappedSuperclass
    table: swp_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
        about:
            type: text
            nullable: true
        externalId:
            type: string
            nullable: true
        emailCanonical:
            type: string
            length: 180
            unique: true
        email:
            type: string
            length: 180
        usernameCanonical:
            type: string
            length: 180
            unique: true
        username:
            type: string
            length: 180
        enabled:
            type: boolean

        password:
            type: string

        roles:
            type: array

        confirmationToken:
            type: string
            length: 180
            unique: true
            nullable: true
